name: Add dataset
on:
  workflow_dispatch:
    inputs:
      numOctocats:
        description: 'Number of Octocats'
        required: false
        default: '1'
      octocatEyeColor:
        description: 'Eye color of the Octocats'
        required: true
    
jobs:
  add_file:
    name: Add dataset to Data Bib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: create_file
        run: |
          touch file2.txt
          git add file2.txt
          git commit -m 'Added file 2'
          git push
