name: Add dataset
on:
  workflow_dispatch:
    inputs:
      dataSetName:
        description: 'Nombre identificativo del dataset'
        required: true
      dataSetFormat:
        description: 'Formato del dataset(json/csv)'
        required: true
        default: 'json'
    
jobs:
  add_file:
    name: Add dataset to Data Bib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: create_file
        run: |
          mkdir /data/${{ INPUT_DATASETNAME }}
          touch /data/${{ INPUT_DATASETNAME }}/dataset.${{ INPUT_DATASETFORMAT }}
          git add /data/${{ INPUT_DATASETNAME }}/dataset.${{ NPUT_DATASETFORMAT }}
          git commit -m 'Added dataset ${{ INPUT_DATASETNAME }}'
          git push
