name: Add dataset
on:
  workflow_dispatch:
    inputs:
      dataSetName:
        description: 'Nombre identificativo del dataset'
        required: true
      dataSetFormat:
        description: 'Formato del dataset(json/csv)'
        required: true
        default: 'json'
    
jobs:
  add_file:
    name: Add dataset to Data Bib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: create_file
        run: |
          mkdir /data/${{ workflow_dispatch.inputs.dataSetName }}
          touch /data/${{ workflow_dispatch.inputs.dataSetName }}/dataset.${{ workflow_dispatch.inputs.dataSetFormat }}
          git add /data/${{ workflow_dispatch.inputs.dataSetName }}/dataset.${{ workflow_dispatch.inputs.dataSetFormat }}
          git commit -m 'Added dataset ${{ workflow_dispatch.inputs.dataSetName }}'
          git push
