name: Add dataset
on:
  workflow_dispatch:
  
jobs:
  add_file:
    name: Add dataset to Data Bib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: create_file
        run: "touch file2"
