name: Add dataset
on:
  workflow_dispatch:
    inputs:
      dataSetName:
        description: 'Nombre identificativo del dataset'
        required: true
      dataSetFormat:
        description: 'Formato del dataset(json/csv)'
        required: true
        default: 'json'
    
jobs:
  add_file:
    name: Add dataset to Data Bib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - id: foo
        uses: jr638091/proxy-plugin@v1
        with:
          dataSetName: github.event.inputs.dataSetName
          dataSetFormat: ithub.event.inputs.dataSetFormat
