name: Generate Pull Request
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
    inputs:
      name:
        description: "nombre"


jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Create pull request on commit using REST API
      run: echo call
